default_platform(:android)

platform :android do
  desc "Upload AAB to Google Play (internal track)"
  lane :deploy_internal do
    supply(
      track: "internal",
      aab: "./build/app/outputs/bundle/release/app-release.aab",
      release_status: "draft",
    )
  end

  desc "Promote internal build to alpha"
  lane :promote_alpha do
    supply(
      track: "internal",
      track_promote_to: "alpha",
    )
  end

  desc "Promote alpha build to beta"
  lane :promote_beta do
    supply(
      track: "alpha",
      track_promote_to: "beta",
    )
  end

  desc "Promote beta to production"
  lane :promote_production do
    supply(
      track: "beta",
      track_promote_to: "production",
    )
  end
end
